name: Build and Release

on:
  push:
    paths:
      - 'main.go'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.x

    - name: Build
      run: |
        go build -o go-aws-s3-cli main.go

    - name: Upload binary to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: go-aws-s3-cli
        asset_name: go-aws-s3-cli-${{ github.sha }}
        tag: ${{ github.ref }}
        overwrite: true
        body: "Built from commit ${{ github.sha }}"