name: Build and Release for Windows

on:
  release:
    types: [created]

jobs:

  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.x

    - name: Build
      run: |
        go build -o go-aws-s3-cli.exe main.go

    - name: Upload binary to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./go-aws-s3-cli.exe
          asset_name: go-aws-s3-cli-windows-${{ github.event.release.tag_name }}.exe
          asset_content_type: application/octet-stream